In [2]:
import pandas as pd

In [8]:
df = pd.read_csv(r"C:\Users\punal\OneDrive\Desktop\Canaan Ed & Tech Internship\Week 3\Task-7\Task-7-sales_data.csv")
df.head()

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
1   Phone  Electronics  20000        10
2   Shirt     Clothing   1500        20
3   Shoes     Clothing   3000        15
4      TV  Electronics  40000         3

In [10]:
# Filter Electronics
electronics = df[df["Category"] == "Electronics"]
electronics

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
1   Phone  Electronics  20000        10
4      TV  Electronics  40000         3

In [12]:
# Filter Price greater than 10000
high_price = df[df["Price"] > 10000]
high_price

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
1   Phone  Electronics  20000        10
4      TV  Electronics  40000         3

In [14]:
# Gropyby
df.groupby("Category")["Price"].mean()

Category
Clothing        2250.000000
Electronics    36666.666667
Name: Price, dtype: float64

In [16]:
df.groupby("Category")["Quantity"].sum()

Category
Clothing       35
Electronics    18
Name: Quantity, dtype: int64

In [18]:
discount = pd.read_csv(r"C:\Users\punal\OneDrive\Desktop\Canaan Ed & Tech Internship\Week 3\Task-7\Task-7-discounts_data.csv")

merged_df = pd.merge(df, discount, on="Product")
merged_df

  Product     Category  Price  Quantity  Discount
0  Laptop  Electronics  50000         5        10
1   Phone  Electronics  20000        10         5
2   Shirt     Clothing   1500        20        15
3   Shoes     Clothing   3000        15        20
4      TV  Electronics  40000         3         8

In [22]:
#Sorting
df.sort_values(by="Price", ascending=False)

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
4      TV  Electronics  40000         3
1   Phone  Electronics  20000        10
3   Shoes     Clothing   3000        15
2   Shirt     Clothing   1500        20

In [24]:
df.sort_values(by="Quantity")

  Product     Category  Price  Quantity
4      TV  Electronics  40000         3
0  Laptop  Electronics  50000         5
1   Phone  Electronics  20000        10
3   Shoes     Clothing   3000        15
2   Shirt     Clothing   1500        20